#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1-bionic AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1-bionic AS build
WORKDIR /src
COPY ["ImageFiltering.Api/ImageFiltering.Api.csproj", "ImageFiltering.Api/"]
COPY ["ImageFiltering.Service/ImageFiltering.Service.csproj", "ImageFiltering.Service/"]
COPY ["ImageFiltering.Shared/ImageFiltering.Shared.csproj", "ImageFiltering.Shared/"]
COPY ["ImageFiltering.Application/ImageFiltering.Application.csproj", "ImageFiltering.Application/"]
RUN dotnet restore "ImageFiltering.Api/ImageFiltering.Api.csproj"
COPY . .
WORKDIR "/src/ImageFiltering.Api"
RUN dotnet build "ImageFiltering.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ImageFiltering.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN apt-get update && apt-get install -y libgdiplus
#ENTRYPOINT ["dotnet", "ImageFiltering.Api.dll"]
CMD ASPNETCORE_URLS=http://*:$PORT dotnet ImageFiltering.Api.dll