export enum ActionTypes {
    LOAD_IMAGE = "LOAD_IMAGE",
    UNLOAD_IMAGE = "UNLOAD_IMAGE",
    RETRIEVE_FILTERED_IMAGE = "RETRIEVE_FILTERED_IMAGE",
    RETRIEVE_FILTERED_IMAGE_LOADING = "RETRIEVE_FILTERED_IMAGE_LOADING",
    ERROR = "ERROR"
}